import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import DotPattern from "@/components/magicui/dot";
import { FloatingDock } from "@/components/aceternity/floating-dock";
import Navbar from '../components/navbar/nav';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-black h-screen")}>
      <Navbar/>
        {children}
        <DotPattern className="-z-10"/>
      </body>
    </html>
  );
}
